import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. DATA LOADING & PREP
# ---------------------------------------------------------
file_path = r'C:\Users\rohan\OneDrive\Desktop\NUS Y1S2\BT2102\Assignment 3\cleaned_beijing_housing.xlsx'
df = pd.read_excel(file_path)

district_mapping = {
    1: "Dongcheng District", 2: "Fengtai District", 3: "Tongzhou District", 
    4: "Daxing District", 5: "Fangshan District", 6: "Changping District", 
    7: "Chaoyang District", 8: "Haidian District", 9: "Shijingshan District", 
    10: "Xicheng District", 11: "Pinggu District", 12: "Mentougou District", 
    13: "Shunyi District"
}
df['district_name'] = df['district'].map(district_mapping)

# Ensure prediction columns exist - if they aren't in your Excel, 
# make sure they are generated by your models before this step.
df['pred_ensemble'] = (df['pred_rf'] * 0.53) + (df['pred_lr'] * 0.47)

# 2. COLOR & SCALE SYNCING
# ---------------------------------------------------------
pareto_order = ["Chaoyang District", "Changping District", "Fengtai District", 
                "Haidian District", "Daxing District", "Pinggu District"]

macro_colors = sns.color_palette("bright", len(pareto_order))
color_map = dict(zip(pareto_order, macro_colors))

# Global zoom limit (99.5th percentile) ensures consistent scaling across all 6 charts
max_vis = df['price'].quantile(0.995)

# 3. THE GENERATION LOOP
# ---------------------------------------------------------
stats_accumulator = []

for dist_name in pareto_order:
    dist_df = df[df['district_name'] == dist_name].copy()
    total = len(dist_df)
    
    # CORRECTED LOGIC: 
    # Underpriced (Value) = Price < Prediction
    # Overpriced (Premium) = Price > Prediction
    under_fv_count = (dist_df['price'] < dist_df['pred_ensemble']).sum()
    over_fv_count = (dist_df['price'] > dist_df['pred_ensemble']).sum()
    
    # Alpha = Deep value (10% or more underpriced)
    under_alpha = (dist_df['price'] < (dist_df['pred_ensemble'] * 0.9)).sum()
    
    alpha_rate = round((under_alpha / total) * 100, 2)
    under_fv_pct = round((under_fv_count / total) * 100, 2)
    over_fv_pct = round((over_fv_count / total) * 100, 2)
    
    stats_accumulator.append({
        "District": dist_name,
        "Listings": total,
        "% Overpriced (Premium)": over_fv_pct,
        "% Underpriced (Value)": under_fv_pct,
        "10% Alpha Rate": f"{alpha_rate}%"
    })

    # Create Plot
    plt.figure(figsize=(10, 10), dpi=300)
    sns.set_style("whitegrid")
    
    # BACKGROUND ZONES FOR CLARITY
    # Shading the Overpriced (Red) and Alpha (Green) areas
    plt.fill_between([0, max_vis], [0, max_vis], [max_vis, max_vis], color='red', alpha=0.02)
    plt.fill_between([0, max_vis], [0, max_vis * 0.9], [0, 0], color='green', alpha=0.05)
    
    # Plot Dots
    plt.scatter(dist_df['pred_ensemble'], dist_df['price'], 
                color=color_map[dist_name], s=25, alpha=0.6, 
                edgecolor='w', linewidth=0.3, label=f'Properties in {dist_name}')
    
    # Reference Lines
    plt.plot([0, max_vis], [0, max_vis], color='#e63946', lw=2, label='Market Parity (Fair Value)')
    plt.plot([0, max_vis], [0, max_vis * 0.9], color='#2a9d8f', ls='--', lw=1.5, label='10% Alpha Boundary')
    
    # Zone Labels
    plt.text(max_vis*0.05, max_vis*0.9, "PREMIUM ZONE", color='red', fontsize=10, fontweight='bold', alpha=0.4)
    plt.text(max_vis*0.65, max_vis*0.1, "ALPHA OPPORTUNITY", color='green', fontsize=10, fontweight='bold', alpha=0.6)

    # Formatting
    plt.title(f"Detailed Mispricing Analysis: {dist_name}\nAlpha Opportunity Rate: {alpha_rate}%", 
              fontsize=16, fontweight='bold', pad=20)
    plt.xlabel("Predicted Fundamental Value (Model)", fontsize=12)
    plt.ylabel("Actual Market Price (Recorded)", fontsize=12)
    
    # Currency Ticks
    plt.gca().xaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'¥{int(x/1000)}k'))
    plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'¥{int(x/1000)}k'))
    
    plt.xlim(0, max_vis)
    plt.ylim(0, max_vis)
    plt.gca().set_aspect('equal', adjustable='box')
    plt.legend(loc='upper left', frameon=True, shadow=True)
    
    # Save
    clean_name = dist_name.replace(" ", "_")
    plt.savefig(f'DeepDive_{clean_name}.png', bbox_inches='tight')
    plt.close()

# 4. FINAL TABLE OUTPUT
# ---------------------------------------------------------
summary_table = pd.DataFrame(stats_accumulator).sort_values("10% Alpha Rate", ascending=False)
print("\n--- FINAL DISTRICT PERFORMANCE TABLE ---")
print(summary_table.to_string(index=False))